language: ruby
rvm:
  - 2.2.1
before_script:
  - rubocop
  - cp config/database.yml.example config/database.yml
  - bundle exec rake db:create db:migrate db:test:prepare

addons:
  code_climate:
    repo_token:
      secure: "lYZY8geoA+gpcdlPWNx1I0FEImaKvOFHbn0zDMK1+te/2un73+EpiiE1dpULV6q62aLSBIAM4m2x1f8pd5f1Mcwl69aY9bIWrLFmUc9xFn4tC4S69u4CRukZO6hAmHxEtuMywC2trG3HhqI/UhN+E2Y8ltF3QHhwzwoHl0YWhfQ="
